name: "webzer.net"
description: "I blog to God but the sky is buggy ..."
author: "Sungsit Sawaiwan"
url: "http://webzer.net"
lang: "th"
ga:  "UA-3757716-3"

permalink: "/node/:title"

markdown: rdiscount
exclude: [CNAME,config.rb,README.md]
